name = "Create The Server"
author = "Create The Server Team"
version = "6.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "defd34746fe12f503c39e0f48d3c2ee310411052df0aec44822cea4fd37a0b7f"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
