name = "Create The Server"
author = "Create The Server Team"
version = "6.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "566b166b3d33f2743a8a7eb968313200b4dc99f27b3ddab0203757f6c0bab9f8"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
