name = "Create The Server"
author = "Create The Server Team"
version = "6.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "441235e5db303d9ed5b18371822166be1d2bf6eb570d618e32cd36da970cb3aa"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
